import type { Achievement } from '@/lib/types/database';

/**
 * Achievement definitions.
 * Moved out of the old lib/data.ts (which contained 970 lines of unused PROJECTS).
 */

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_stitch',
    key: 'first_stitch',
    name: 'First Stitch',
    description: 'Start your first project',
    icon: 'scissors',
    xp_reward: 25,
    criteria: { type: 'projects_started', count: 1 },
  },
  {
    id: 'thread_collector',
    key: 'thread_collector',
    name: 'Thread Collector',
    description: 'Start 5 projects',
    icon: 'layers',
    xp_reward: 50,
    criteria: { type: 'projects_started', count: 5 },
  },
  {
    id: 'finished_article',
    key: 'finished_article',
    name: 'Finished Article',
    description: 'Complete your first project',
    icon: 'check-circle',
    xp_reward: 50,
    criteria: { type: 'projects_completed', count: 1 },
  },
  {
    id: 'yarn_whisperer',
    key: 'yarn_whisperer',
    name: 'Yarn Whisperer',
    description: 'Complete your first knitting project',
    icon: 'heart',
    xp_reward: 50,
    criteria: { type: 'category_completed', category: 'knitting', count: 1 },
  },
  {
    id: 'hook_line_sinker',
    key: 'hook_line_sinker',
    name: 'Hook, Line & Sinker',
    description: 'Complete your first crochet project',
    icon: 'anchor',
    xp_reward: 50,
    criteria: { type: 'category_completed', category: 'crochet', count: 1 },
  },
  {
    id: 'snap_happy',
    key: 'snap_happy',
    name: 'Snap Happy',
    description: 'Upload 10 photos',
    icon: 'camera',
    xp_reward: 50,
    criteria: { type: 'photos_uploaded', count: 10 },
  },
  {
    id: 'perfectionist',
    key: 'perfectionist',
    name: 'Perfectionist',
    description: 'Give a project 5 stars',
    icon: 'star',
    xp_reward: 25,
    criteria: { type: 'five_star_rating', count: 1 },
  },
  {
    id: 'marathon_maker',
    key: 'marathon_maker',
    name: 'Marathon Maker',
    description: 'Log 50+ hours total crafting',
    icon: 'clock',
    xp_reward: 100,
    criteria: { type: 'hours_logged', count: 50 },
  },
  {
    id: 'streak_master',
    key: 'streak_master',
    name: 'Streak Master',
    description: 'Maintain a 30-day crafting streak',
    icon: 'flame',
    xp_reward: 200,
    criteria: { type: 'streak', count: 30 },
  },
  {
    id: 'ach-016',
    key: 'journal_keeper',
    name: 'Journal Keeper',
    description: 'Log 5 entries in your craft journal',
    icon: 'book-open',
    xp_reward: 25,
    criteria: { type: 'journal_entries', count: 5 },
  },
  {
    id: 'ach-017',
    key: 'favorites_collector',
    name: 'Favourites Collector',
    description: 'Add 10 patterns to your favourites',
    icon: 'heart',
    xp_reward: 15,
    criteria: { type: 'favorites_count', count: 10 },
  },
  {
    id: 'ach-018',
    key: 'craft_mode_master',
    name: 'Craft Mode Master',
    description: 'Complete 5 craft mode sessions',
    icon: 'zap',
    xp_reward: 25,
    criteria: { type: 'craft_mode_sessions', count: 5 },
  },
  {
    id: 'ach-019',
    key: 'social_crafter',
    name: 'Social Crafter',
    description: 'Share 3 patterns with friends',
    icon: 'share-2',
    xp_reward: 15,
    criteria: { type: 'projects_shared', count: 3 },
  },
];
