import type { Project, Achievement } from '@/lib/types/database';

export const PROJECTS: Project[] = [
  // ============================================
  // SEWING PROJECTS (10)
  // ============================================
  {
    id: 'project-001',
    title: 'Canvas Tote Bag',
    description: 'A sturdy, reusable tote bag perfect for shopping or carrying craft supplies. This beginner-friendly project teaches straight seams and basic bag construction.',
    category: 'sewing',
    difficulty: 'beginner',
    estimated_time: '2-3 hours',
    cover_image: null,
    materials: [
      { name: 'Cotton canvas fabric', quantity: '1 metre', estimated_cost: 8.00 },
      { name: 'Matching thread', quantity: '1 spool', estimated_cost: 2.50 },
      { name: 'Fabric scissors', quantity: '1 pair', estimated_cost: 6.00 },
      { name: 'Pins', quantity: '1 pack', estimated_cost: 1.50 },
      { name: 'Iron', quantity: '1', estimated_cost: 0 },
    ],
    steps: [
      { order: 1, title: 'Cut the Fabric', description: 'Cut two rectangles of canvas, each 40cm x 45cm for the bag body. Cut two strips 8cm x 60cm for the handles.', tip: 'Use a rotary cutter and ruler for perfectly straight edges.' },
      { order: 2, title: 'Hem the Top Edge', description: 'Fold the top edge of each rectangle down 1cm, press with an iron, then fold again 2cm. Pin and sew along the bottom fold.' },
      { order: 3, title: 'Make the Handles', description: 'Fold each handle strip in half lengthways, wrong sides together. Open, fold each raw edge to the centre crease, then fold in half again. Press and topstitch along both long edges.' },
      { order: 4, title: 'Attach the Handles', description: 'Pin each handle to the right side of one bag piece, 10cm from each side edge. The handle ends should sit 2cm below the top hem. Sew a square with an X through it to secure each end.' },
      { order: 5, title: 'Sew the Bag Together', description: 'Place the two bag pieces right sides together. Pin and sew along the bottom and both sides using a 1.5cm seam allowance.', tip: 'Backstitch at the start and end of each seam for strength.' },
      { order: 6, title: 'Box the Corners', description: 'Flatten each bottom corner into a triangle, measure 5cm from the point, and sew across. This creates a flat bottom for the bag.' },
      { order: 7, title: 'Finish and Turn', description: 'Trim the corner triangles, turn the bag right side out, and press with an iron. Your tote is complete!' },
    ],
    tips: 'Press all seams as you go — it makes a huge difference to the finished look. Choose a medium-weight canvas for structure. You can add a pocket to the inside before sewing the pieces together.',
    cost_estimate: '£10 - £18',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-002',
    title: 'Envelope Cushion Cover',
    description: 'A simple cushion cover with an envelope back opening — no zip required! Great for refreshing your home décor.',
    category: 'sewing',
    difficulty: 'beginner',
    estimated_time: '1-2 hours',
    cover_image: null,
    materials: [
      { name: 'Cotton fabric', quantity: '0.75 metre', estimated_cost: 6.00 },
      { name: 'Matching thread', quantity: '1 spool', estimated_cost: 2.50 },
      { name: 'Cushion pad (45cm)', quantity: '1', estimated_cost: 5.00 },
      { name: 'Pins', quantity: '1 pack', estimated_cost: 1.50 },
    ],
    steps: [
      { order: 1, title: 'Cut the Fabric', description: 'Cut one front piece 47cm x 47cm. Cut two back pieces, each 47cm x 32cm.' },
      { order: 2, title: 'Hem the Back Pieces', description: 'On each back piece, fold one long edge over 1cm, press, fold again 2cm, and sew along the fold.' },
      { order: 3, title: 'Layer the Pieces', description: 'Place the front piece right side up. Lay the two back pieces on top, right sides down, with hemmed edges overlapping in the centre.' },
      { order: 4, title: 'Pin and Sew', description: 'Pin around all four edges. Sew around the entire perimeter using a 1cm seam allowance.', tip: 'Clip the corners diagonally before turning to reduce bulk.' },
      { order: 5, title: 'Turn and Insert', description: 'Turn right side out through the envelope opening, push out the corners with a chopstick, press flat, and insert your cushion pad.' },
    ],
    tips: 'Choose a fabric that complements your room. Wash and press your fabric before cutting to prevent shrinkage later.',
    cost_estimate: '£8 - £15',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-003',
    title: 'Gathered Skirt',
    description: 'A classic gathered skirt with an elasticated waist. Flattering and comfortable — perfect for all skill levels.',
    category: 'sewing',
    difficulty: 'intermediate',
    estimated_time: '3-4 hours',
    cover_image: null,
    materials: [
      { name: 'Cotton or viscose fabric', quantity: '1.5 metres', estimated_cost: 12.00 },
      { name: 'Elastic (2.5cm wide)', quantity: 'waist measurement + 5cm', estimated_cost: 2.00 },
      { name: 'Matching thread', quantity: '1 spool', estimated_cost: 2.50 },
      { name: 'Safety pin', quantity: '1', estimated_cost: 0.50 },
    ],
    steps: [
      { order: 1, title: 'Measure and Cut', description: 'Measure your desired skirt length and add 6cm for the waistband casing and hem. Cut a rectangle the full width of the fabric.' },
      { order: 2, title: 'Sew the Side Seam', description: 'Fold the fabric in half, right sides together. Sew along the short edge to create a tube, leaving a 3cm opening at the top for the elastic casing.' },
      { order: 3, title: 'Create the Waistband Casing', description: 'Fold the top edge down 1cm, press, then fold again 3cm. Sew close to the lower fold, leaving the opening unstitched.' },
      { order: 4, title: 'Insert the Elastic', description: 'Attach a safety pin to one end of the elastic and thread it through the casing. Try on for fit, overlap the ends by 2cm, and sew them together securely.' },
      { order: 5, title: 'Close the Casing', description: 'Distribute the gathers evenly around the waist. Sew the casing opening closed.' },
      { order: 6, title: 'Hem the Bottom', description: 'Try the skirt on and mark your desired length. Fold up 1cm, press, fold again 2cm, and sew the hem.', tip: 'Use a blind hem stitch for a professional finish.' },
    ],
    tips: 'A lightweight cotton or viscose drapes beautifully for this style. Add pockets by inserting them into the side seam before closing it.',
    cost_estimate: '£12 - £17',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-004',
    title: 'Drawstring Pouch',
    description: 'A versatile little bag ideal for storing jewellery, crafting supplies, or small gifts.',
    category: 'sewing',
    difficulty: 'beginner',
    estimated_time: '45 minutes',
    cover_image: null,
    materials: [
      { name: 'Cotton fabric', quantity: '0.25 metre', estimated_cost: 3.00 },
      { name: 'Cord or ribbon', quantity: '60cm', estimated_cost: 1.50 },
      { name: 'Matching thread', quantity: '1 spool', estimated_cost: 2.50 },
      { name: 'Safety pin', quantity: '1', estimated_cost: 0.50 },
    ],
    steps: [
      { order: 1, title: 'Cut the Fabric', description: 'Cut two rectangles, each 18cm x 22cm.' },
      { order: 2, title: 'Create the Casing', description: 'On each piece, fold the top edge down 1cm, press, fold again 2cm, and sew along the bottom fold.' },
      { order: 3, title: 'Sew the Body', description: 'Place pieces right sides together. Sew the sides and bottom, starting 3cm below the top to leave openings for the drawstring.', tip: 'Backstitch at the casing opening for reinforcement.' },
      { order: 4, title: 'Thread the Cord', description: 'Use a safety pin to thread the cord through one casing opening, all the way around, and out the same opening. Knot both ends together.' },
      { order: 5, title: 'Turn and Finish', description: 'Turn right side out and pull the cord to close. Your pouch is ready!' },
    ],
    tips: 'Use contrasting fabric for the inside for a pop of colour when the pouch is open.',
    cost_estimate: '£4 - £8',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-005',
    title: 'Classic Apron',
    description: 'A practical kitchen apron with an adjustable neck strap and waist ties. Makes a lovely handmade gift.',
    category: 'sewing',
    difficulty: 'intermediate',
    estimated_time: '2-3 hours',
    cover_image: null,
    materials: [
      { name: 'Cotton fabric', quantity: '1 metre', estimated_cost: 8.00 },
      { name: 'Matching thread', quantity: '1 spool', estimated_cost: 2.50 },
      { name: 'Bias binding', quantity: '3 metres', estimated_cost: 3.00 },
    ],
    steps: [
      { order: 1, title: 'Cut the Main Piece', description: 'Cut a rectangle 70cm wide x 85cm long. Shape the top by tapering from 35cm at the chest to 70cm at the hips.' },
      { order: 2, title: 'Hem the Sides', description: 'Fold each side edge over 0.5cm, then again 1cm. Press and sew.' },
      { order: 3, title: 'Add the Pocket', description: 'Cut a 20cm x 18cm rectangle, hem the top, fold under the other edges 1cm, and topstitch it to the front of the apron.' },
      { order: 4, title: 'Make the Neck Strap', description: 'Cut bias binding to 70cm, fold in half lengthways, and sew along the open edge. Attach to the top corners of the apron bib.' },
      { order: 5, title: 'Make Waist Ties', description: 'Cut two strips of bias binding, each 60cm long. Fold and sew as above, then attach to the waist sides.' },
      { order: 6, title: 'Hem the Bottom', description: 'Fold up 1cm, press, fold again 2cm, and sew. Give everything a final press.' },
    ],
    tips: 'Pre-wash cotton fabric to prevent shrinkage. Linen-cotton blends work beautifully for aprons — they soften with every wash.',
    cost_estimate: '£10 - £14',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-006',
    title: 'Patchwork Quilt Block',
    description: 'Learn the basics of patchwork by creating a single quilt block. A building block for larger projects!',
    category: 'sewing',
    difficulty: 'intermediate',
    estimated_time: '2-3 hours',
    cover_image: null,
    materials: [
      { name: 'Assorted cotton fabrics', quantity: '4-5 fat quarters', estimated_cost: 10.00 },
      { name: 'Matching thread', quantity: '1 spool', estimated_cost: 2.50 },
      { name: 'Rotary cutter', quantity: '1', estimated_cost: 8.00 },
      { name: 'Quilting ruler', quantity: '1', estimated_cost: 6.00 },
      { name: 'Cutting mat', quantity: '1', estimated_cost: 10.00 },
    ],
    steps: [
      { order: 1, title: 'Choose Your Pattern', description: 'Select a simple nine-patch design. Choose 2-3 coordinating fabrics in light, medium, and dark values.' },
      { order: 2, title: 'Cut the Squares', description: 'Cut nine squares, each 12cm x 12cm. Arrange them in a 3x3 grid, alternating light and dark.' },
      { order: 3, title: 'Sew the Rows', description: 'Sew the three squares in each row together using a 0.7cm seam allowance. Press seams to one side, alternating direction for each row.' },
      { order: 4, title: 'Join the Rows', description: 'Pin rows together, nesting the seams for precision. Sew the three rows together.', tip: 'Nested seams (pressed in opposite directions) help your intersections line up perfectly.' },
      { order: 5, title: 'Press and Square Up', description: 'Press the finished block and trim to ensure all edges are straight and corners are square.' },
    ],
    tips: 'Accuracy is key in patchwork — a consistent seam allowance makes everything line up. Use a scant 0.7cm seam for best results.',
    cost_estimate: '£15 - £37',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-007',
    title: 'Lined Zipper Pouch',
    description: 'A zip-top pouch perfect for cosmetics, pencils, or craft tools. Learning to sew a zip is easier than you think!',
    category: 'sewing',
    difficulty: 'intermediate',
    estimated_time: '1.5-2 hours',
    cover_image: null,
    materials: [
      { name: 'Outer fabric', quantity: '0.25 metre', estimated_cost: 4.00 },
      { name: 'Lining fabric', quantity: '0.25 metre', estimated_cost: 3.00 },
      { name: 'Zip (20cm)', quantity: '1', estimated_cost: 1.00 },
      { name: 'Matching thread', quantity: '1 spool', estimated_cost: 2.50 },
    ],
    steps: [
      { order: 1, title: 'Cut the Pieces', description: 'Cut two outer pieces and two lining pieces, each 24cm x 16cm.' },
      { order: 2, title: 'Attach the Zip (Side 1)', description: 'Layer one outer piece (right side up), the zip (face down), and one lining piece (right side down). Sew along the zip edge.' },
      { order: 3, title: 'Attach the Zip (Side 2)', description: 'Repeat with the remaining pieces on the other side of the zip.' },
      { order: 4, title: 'Sew the Pouch', description: 'Open out and pin outer pieces together and lining pieces together. Sew around, leaving a 6cm turning gap in the lining bottom.', tip: 'Open the zip halfway before sewing — you will need it to turn the pouch right side out!' },
      { order: 5, title: 'Turn and Close', description: 'Turn right side out through the gap. Hand-stitch or machine-stitch the gap closed. Push the lining inside the pouch and press.' },
    ],
    tips: 'Use a zipper foot on your machine for neat stitching close to the zip teeth. A contrasting lining adds a lovely surprise when you open the pouch.',
    cost_estimate: '£6 - £11',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-008',
    title: 'Scrunchie',
    description: 'The quickest sewing project — a fabric hair scrunchie! Perfect for using up fabric scraps.',
    category: 'sewing',
    difficulty: 'beginner',
    estimated_time: '20-30 minutes',
    cover_image: null,
    materials: [
      { name: 'Fabric strip', quantity: '50cm x 12cm', estimated_cost: 1.00 },
      { name: 'Elastic (0.5cm wide)', quantity: '20cm', estimated_cost: 0.50 },
      { name: 'Matching thread', quantity: '1 spool', estimated_cost: 2.50 },
      { name: 'Safety pin', quantity: '1', estimated_cost: 0.50 },
    ],
    steps: [
      { order: 1, title: 'Cut and Fold', description: 'Cut your fabric strip 50cm x 12cm. Fold in half lengthways, right sides together.' },
      { order: 2, title: 'Sew the Tube', description: 'Sew along the long open edge with a 1cm seam allowance, creating a tube. Leave both short ends open.' },
      { order: 3, title: 'Turn Right Side Out', description: 'Use a safety pin to pull the tube right side out.' },
      { order: 4, title: 'Insert the Elastic', description: 'Thread the elastic through the tube. Overlap the ends by 1cm and sew securely.' },
      { order: 5, title: 'Close the Scrunchie', description: 'Tuck one raw end inside the other and hand-stitch closed with a ladder stitch.' },
    ],
    tips: 'Satin, velvet, and cotton all make gorgeous scrunchies. Make several in different fabrics to match your outfits!',
    cost_estimate: '£1 - £5',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-009',
    title: 'Bucket Hat',
    description: 'A trendy reversible bucket hat. Wear it two ways with contrasting fabrics on each side!',
    category: 'sewing',
    difficulty: 'advanced',
    estimated_time: '3-4 hours',
    cover_image: null,
    materials: [
      { name: 'Outer fabric', quantity: '0.5 metre', estimated_cost: 6.00 },
      { name: 'Contrasting fabric (lining)', quantity: '0.5 metre', estimated_cost: 6.00 },
      { name: 'Medium-weight interfacing', quantity: '0.25 metre', estimated_cost: 3.00 },
      { name: 'Matching thread', quantity: '1 spool', estimated_cost: 2.50 },
    ],
    steps: [
      { order: 1, title: 'Cut the Pattern Pieces', description: 'For each fabric, cut: 1 crown circle (20cm diameter), 4 side panels (tapered from 18cm to 16cm, height 12cm), and 1 brim (outer diameter 38cm, inner diameter 20cm).' },
      { order: 2, title: 'Sew the Side Panels', description: 'Sew the four side panels together to form a ring. Press seams open.' },
      { order: 3, title: 'Attach the Crown', description: 'Pin and sew the crown circle to the top of the side panel ring, easing around the curve. Clip the seam allowance for a smooth finish.' },
      { order: 4, title: 'Attach the Brim', description: 'Sew the inner edge of the brim to the bottom of the side panels, right sides together.' },
      { order: 5, title: 'Make the Lining', description: 'Repeat steps 2-4 with the contrasting fabric. Apply interfacing to the lining brim for structure.' },
      { order: 6, title: 'Join Outer and Lining', description: 'Place outer hat and lining right sides together, matching the brim edges. Sew around the outer brim edge, leaving a 10cm gap for turning.' },
      { order: 7, title: 'Turn and Topstitch', description: 'Turn right side out, press the brim flat, and topstitch around the brim edge to close the gap and add structure.' },
    ],
    tips: 'Add stiffness to the brim with interfacing or starching. This hat looks great in denim, canvas, or printed cotton.',
    cost_estimate: '£12 - £18',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-010',
    title: 'Fabric Coasters (Set of 4)',
    description: 'Protect your surfaces in style with these quilted fabric coasters. A great stash-busting project.',
    category: 'sewing',
    difficulty: 'beginner',
    estimated_time: '1-2 hours',
    cover_image: null,
    materials: [
      { name: 'Cotton fabric scraps', quantity: 'assorted', estimated_cost: 2.00 },
      { name: 'Batting or wadding', quantity: 'small piece', estimated_cost: 2.00 },
      { name: 'Matching thread', quantity: '1 spool', estimated_cost: 2.50 },
    ],
    steps: [
      { order: 1, title: 'Cut the Pieces', description: 'For each coaster, cut two fabric squares 12cm x 12cm and one batting square 12cm x 12cm.' },
      { order: 2, title: 'Make a Sandwich', description: 'Layer: backing (right side down), batting, top fabric (right side up).' },
      { order: 3, title: 'Quilt the Layers', description: 'Sew diagonal lines across the sandwich in both directions to create a crosshatch quilting pattern.' },
      { order: 4, title: 'Trim and Bind', description: 'Trim all layers even. Fold the backing over to the front to create a narrow binding, or use bias tape around the edges.' },
      { order: 5, title: 'Repeat', description: 'Make three more coasters following the same steps. Mix and match fabrics for a charming set!' },
    ],
    tips: 'Use coordinating prints from the same fabric range for a cohesive set. These make lovely gifts!',
    cost_estimate: '£3 - £7',
    created_at: '2025-01-01T00:00:00.000Z',
  },

  // ============================================
  // KNITTING PROJECTS (10)
  // ============================================
  {
    id: 'project-011',
    title: "Beginner's Scarf",
    description: 'A classic garter stitch scarf — the perfect first knitting project. Uses just one stitch throughout!',
    category: 'knitting',
    difficulty: 'beginner',
    estimated_time: '1-2 weeks',
    cover_image: null,
    materials: [
      { name: 'Chunky yarn', quantity: '2 skeins (200g)', estimated_cost: 8.00 },
      { name: '8mm knitting needles', quantity: '1 pair', estimated_cost: 4.00 },
      { name: 'Darning needle', quantity: '1', estimated_cost: 1.50 },
    ],
    steps: [
      { order: 1, title: 'Cast On', description: 'Cast on 25 stitches using the long-tail method. This gives a neat, stretchy edge.', tip: 'If long-tail cast on is tricky, the knitted cast on works just as well for scarves.' },
      { order: 2, title: 'Knit Every Row', description: 'Knit every stitch on every row. This creates garter stitch — a lovely squishy, reversible fabric.' },
      { order: 3, title: 'Check Your Tension', description: 'After a few rows, check your tension is even. The fabric should feel relaxed, not tight.' },
      { order: 4, title: 'Keep Going', description: 'Continue knitting until your scarf measures approximately 150cm long, or until you nearly run out of yarn.' },
      { order: 5, title: 'Cast Off', description: 'Knit two stitches, pass the first over the second. Continue across the row. Cut the yarn and pull through the last stitch.' },
      { order: 6, title: 'Weave in Ends', description: 'Thread the darning needle with each yarn tail and weave it through the back of several stitches. Trim neatly.' },
    ],
    tips: 'Choose a light-coloured yarn so you can see your stitches clearly while learning. Chunky yarn knits up quickly, which keeps you motivated!',
    cost_estimate: '£10 - £14',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-012',
    title: 'Ribbed Beanie',
    description: 'A cosy, stretchy beanie in 2x2 rib. Knit in the round on circular needles for a seamless finish.',
    category: 'knitting',
    difficulty: 'intermediate',
    estimated_time: '3-5 hours',
    cover_image: null,
    materials: [
      { name: 'DK weight yarn', quantity: '1 skein (100g)', estimated_cost: 5.00 },
      { name: '4mm circular needles (40cm)', quantity: '1 set', estimated_cost: 6.00 },
      { name: '4mm double-pointed needles', quantity: '1 set', estimated_cost: 4.00 },
      { name: 'Stitch marker', quantity: '1', estimated_cost: 1.00 },
      { name: 'Darning needle', quantity: '1', estimated_cost: 1.50 },
    ],
    steps: [
      { order: 1, title: 'Cast On', description: 'Cast on 88 stitches onto the circular needles. Join in the round, being careful not to twist. Place a stitch marker at the start.' },
      { order: 2, title: 'Knit the Ribbing', description: 'Work in *K2, P2* ribbing for every round until the hat measures 18cm from the cast-on edge.' },
      { order: 3, title: 'Begin Decreases', description: 'Switch to double-pointed needles when it gets tight. Decrease round: *K2, P2tog* around. Next round: *K2, P1* around.' },
      { order: 4, title: 'Continue Decreasing', description: 'Next decrease round: *K2tog, P1* around. Then *K1, P1* around. Then *K2tog* around.' },
      { order: 5, title: 'Close the Top', description: 'Cut the yarn, thread through the remaining stitches, pull tight, and secure on the inside.' },
      { order: 6, title: 'Finish', description: 'Weave in all ends. Block gently by dampening and laying flat to shape.' },
    ],
    tips: "Try your beanie on as you go to check the length before decreasing. Everyone's head is different! Superwash wool is great because you can machine wash the finished hat.",
    cost_estimate: '£12 - £18',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-013',
    title: 'Cotton Dishcloth',
    description: "A practical project that teaches knit, purl, and increases/decreases. You'll use this every day!",
    category: 'knitting',
    difficulty: 'beginner',
    estimated_time: '2-3 hours',
    cover_image: null,
    materials: [
      { name: 'Cotton DK yarn', quantity: '1 ball (50g)', estimated_cost: 3.00 },
      { name: '4mm knitting needles', quantity: '1 pair', estimated_cost: 4.00 },
    ],
    steps: [
      { order: 1, title: 'Cast On', description: 'Cast on 4 stitches.' },
      { order: 2, title: 'Increase Section', description: 'Every row: Knit 2, yarn over, knit to end. This creates a diagonal increase and a decorative eyelet border.' },
      { order: 3, title: 'Continue Increasing', description: 'Repeat until you have 40 stitches on your needles. The cloth will form a triangle shape.' },
      { order: 4, title: 'Decrease Section', description: 'Every row: Knit 1, K2tog, yarn over, K2tog, knit to end.' },
      { order: 5, title: 'Continue Decreasing', description: 'Repeat until 4 stitches remain.' },
      { order: 6, title: 'Cast Off', description: 'Cast off the remaining 4 stitches and weave in the ends.' },
    ],
    tips: '100% cotton yarn is essential for dishcloths — it absorbs water beautifully and gets better with use. Make a stack in different colours!',
    cost_estimate: '£3 - £7',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-014',
    title: 'Baby Blanket',
    description: 'A beautiful seed stitch baby blanket — soft, reversible, and full of texture. A treasured handmade gift.',
    category: 'knitting',
    difficulty: 'beginner',
    estimated_time: '2-3 weeks',
    cover_image: null,
    materials: [
      { name: 'Baby DK yarn (soft acrylic or cotton blend)', quantity: '4 skeins (400g)', estimated_cost: 16.00 },
      { name: '5mm knitting needles', quantity: '1 pair (long)', estimated_cost: 5.00 },
      { name: 'Darning needle', quantity: '1', estimated_cost: 1.50 },
    ],
    steps: [
      { order: 1, title: 'Cast On', description: 'Cast on 120 stitches. This will create a blanket approximately 75cm wide.' },
      { order: 2, title: 'Seed Stitch Border', description: 'Work 8 rows of seed stitch (K1, P1 across, alternating each row) for the bottom border.' },
      { order: 3, title: 'Body of the Blanket', description: 'Row 1: (K1, P1) x 5, knit to last 10 sts, (P1, K1) x 5. Row 2: (K1, P1) x 5, purl to last 10 sts, (P1, K1) x 5. This creates a stocking stitch centre with seed stitch borders.' },
      { order: 4, title: 'Keep Knitting', description: 'Repeat the body rows until the blanket measures approximately 90cm long.' },
      { order: 5, title: 'Top Border', description: 'Work 8 rows of seed stitch across all stitches.' },
      { order: 6, title: 'Cast Off and Finish', description: 'Cast off loosely in seed stitch pattern. Weave in all ends and block gently.' },
    ],
    tips: 'Choose a machine-washable yarn for baby items — parents will thank you! Block the blanket after finishing for a professional look.',
    cost_estimate: '£16 - £23',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-015',
    title: 'Fingerless Gloves',
    description: 'Cosy fingerless gloves knit in the round. Keep your hands warm whilst keeping your fingers free for crafting!',
    category: 'knitting',
    difficulty: 'intermediate',
    estimated_time: '4-6 hours',
    cover_image: null,
    materials: [
      { name: 'DK weight yarn', quantity: '1 skein (100g)', estimated_cost: 5.00 },
      { name: '3.5mm double-pointed needles', quantity: '1 set', estimated_cost: 4.50 },
      { name: 'Stitch markers', quantity: '2', estimated_cost: 1.00 },
      { name: 'Waste yarn', quantity: 'small piece', estimated_cost: 0 },
    ],
    steps: [
      { order: 1, title: 'Cast On', description: 'Cast on 40 stitches, distributed evenly across 4 DPNs (10 per needle). Join in the round.' },
      { order: 2, title: 'Knit the Cuff', description: 'Work 15 rounds of *K2, P2* ribbing.' },
      { order: 3, title: 'Knit the Hand', description: 'Switch to stocking stitch (knit every round) for 10 rounds.' },
      { order: 4, title: 'Thumb Gusset', description: 'Place markers around 2 stitches on the palm side. Increase 1 stitch before and after these stitches every other round until you have 12 gusset stitches.' },
      { order: 5, title: 'Set Aside Thumb', description: 'Place the 12 thumb stitches on waste yarn. Cast on 2 stitches over the gap and continue knitting in the round.' },
      { order: 6, title: 'Finish the Hand', description: 'Knit 8 more rounds, then work 4 rounds of *K2, P2* ribbing. Cast off.' },
      { order: 7, title: 'Knit the Thumb', description: 'Pick up the 12 held stitches plus 2 from the cast-on edge. Knit 6 rounds, then work 2 rounds of ribbing. Cast off.' },
      { order: 8, title: 'Second Glove', description: 'Make the second glove, placing the thumb gusset on the opposite side.' },
    ],
    tips: "Try them on as you go! The beauty of fingerless gloves is that the fit doesn't need to be as precise as full gloves.",
    cost_estimate: '£5 - £11',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-016',
    title: 'Cable Knit Headband',
    description: "A chunky cable headband — impressive looking but simpler than you'd think. Learn to cable without a cable needle!",
    category: 'knitting',
    difficulty: 'intermediate',
    estimated_time: '2-3 hours',
    cover_image: null,
    materials: [
      { name: 'Aran weight yarn', quantity: '1 skein (100g)', estimated_cost: 5.00 },
      { name: '5mm knitting needles', quantity: '1 pair', estimated_cost: 4.00 },
      { name: 'Cable needle', quantity: '1', estimated_cost: 2.00 },
      { name: 'Darning needle', quantity: '1', estimated_cost: 1.50 },
    ],
    steps: [
      { order: 1, title: 'Cast On', description: 'Cast on 22 stitches.' },
      { order: 2, title: 'Set Up the Pattern', description: 'Row 1 (RS): P3, K4, P4, K4, P4, K4, P3. Row 2 (WS): K3, P4, K4, P4, K4, P4, K3.' },
      { order: 3, title: 'Work the Cables', description: 'Every 6th right-side row, work the cable: slip 2 stitches to cable needle and hold at front, K2, then K2 from cable needle.' },
      { order: 4, title: 'Continue the Pattern', description: 'Repeat the pattern rows until the headband measures approximately 50cm (or fits around your head with a slight stretch).' },
      { order: 5, title: 'Graft or Seam the Ends', description: 'Either graft the two ends together using Kitchener stitch, or cast off and sew the ends together neatly.' },
      { order: 6, title: 'Finish', description: 'Weave in ends and add a twist at the seam for a turban style if desired.' },
    ],
    tips: "Cable crossings are just rearranging stitches — once you get the rhythm, it's addictive! A cable needle is helpful but you can also just pinch the stitches.",
    cost_estimate: '£5 - £13',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-017',
    title: 'Simple Socks',
    description: 'Your first pair of hand-knit socks! Knit top-down with a heel flap for a comfortable fit.',
    category: 'knitting',
    difficulty: 'advanced',
    estimated_time: '1-2 weeks',
    cover_image: null,
    materials: [
      { name: 'Sock yarn (4-ply)', quantity: '1 skein (100g)', estimated_cost: 7.00 },
      { name: '2.5mm double-pointed needles', quantity: '1 set', estimated_cost: 5.00 },
      { name: 'Stitch markers', quantity: '2', estimated_cost: 1.00 },
    ],
    steps: [
      { order: 1, title: 'Cast On and Cuff', description: 'Cast on 60 stitches, divide across 4 DPNs. Work 15 rounds of *K2, P2* ribbing.' },
      { order: 2, title: 'Knit the Leg', description: 'Work in stocking stitch for 15cm from the cast-on edge.' },
      { order: 3, title: 'Heel Flap', description: 'Work back and forth on 30 stitches: Row 1: *Sl1, K1* across. Row 2: Sl1, purl across. Repeat for 30 rows.' },
      { order: 4, title: 'Turn the Heel', description: 'Short rows to shape the heel cup. K17, SSK, K1, turn. P6, P2tog, P1, turn. Continue until all side stitches are worked.' },
      { order: 5, title: 'Gusset', description: "Pick up stitches along each side of the heel flap. Decrease every other round at each side until you're back to 60 stitches." },
      { order: 6, title: 'Foot', description: 'Knit in the round until the foot measures 5cm less than your total foot length.' },
      { order: 7, title: 'Toe Decreases', description: 'Decrease 4 stitches every other round (at each side of the top and bottom) until 12 stitches remain.' },
      { order: 8, title: 'Graft the Toe', description: 'Use Kitchener stitch to close the toe. Weave in all ends and make the second sock!' },
    ],
    tips: 'The second sock is always faster than the first! Sock yarn contains nylon for durability — pure wool wears through too quickly at the heel.',
    cost_estimate: '£7 - £13',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-018',
    title: 'Chunky Throw Blanket',
    description: 'A super-chunky knitted throw that works up quickly on big needles. Instant cosy vibes!',
    category: 'knitting',
    difficulty: 'beginner',
    estimated_time: '1-2 weeks',
    cover_image: null,
    materials: [
      { name: 'Super chunky yarn', quantity: '6 skeins (600g)', estimated_cost: 30.00 },
      { name: '12mm knitting needles', quantity: '1 pair (circular, 100cm)', estimated_cost: 8.00 },
    ],
    steps: [
      { order: 1, title: 'Cast On', description: 'Cast on 60 stitches onto the circular needles (used flat, not joined in the round).' },
      { order: 2, title: 'Knit the Body', description: 'Work in garter stitch (knit every row) until the blanket measures approximately 120cm.', tip: 'Garter stitch in chunky yarn creates the perfect squishy, textured fabric.' },
      { order: 3, title: 'Change Colours (Optional)', description: 'For stripes, change yarn colour every 10-20 rows. Carry the unused yarn up the side loosely.' },
      { order: 4, title: 'Cast Off', description: 'Cast off loosely — you want the edge to be stretchy.' },
      { order: 5, title: 'Weave In and Block', description: 'Weave in all yarn tails and lay flat to even out the stitches.' },
    ],
    tips: "Super chunky yarn on big needles means you'll see progress fast! Choose a soft acrylic blend for easy care and budget-friendliness.",
    cost_estimate: '£30 - £38',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-019',
    title: 'Tea Cosy',
    description: 'Keep your tea warm in style with this classic knitted tea cosy. A quintessentially British project!',
    category: 'knitting',
    difficulty: 'intermediate',
    estimated_time: '3-5 hours',
    cover_image: null,
    materials: [
      { name: 'DK weight yarn', quantity: '2 skeins (different colours)', estimated_cost: 8.00 },
      { name: '4mm knitting needles', quantity: '1 pair', estimated_cost: 4.00 },
      { name: 'Darning needle', quantity: '1', estimated_cost: 1.50 },
    ],
    steps: [
      { order: 1, title: 'Knit Two Panels', description: 'Cast on 40 stitches. Knit in stocking stitch for 20cm, then shape the top with decreases (K2tog at each end every RS row) until 10 stitches remain. Cast off.' },
      { order: 2, title: 'Add Stripes', description: 'Alternate colours every 4 rows for a striped effect, or use a single colour.' },
      { order: 3, title: 'Make a Loop', description: 'Knit a small i-cord (4 stitches, 8cm long) for the top loop.' },
      { order: 4, title: 'Seam the Panels', description: 'Sew the two panels together at the top and sides, leaving gaps for the spout and handle.' },
      { order: 5, title: 'Attach the Loop', description: 'Sew the i-cord loop to the centre top and weave in all ends.' },
    ],
    tips: 'Measure your teapot first! Mark where the spout and handle openings need to be before seaming.',
    cost_estimate: '£8 - £14',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-020',
    title: 'Knitted Toy Bear',
    description: 'An adorable stuffed bear knitted in stocking stitch. A cherished handmade toy for a little one.',
    category: 'knitting',
    difficulty: 'advanced',
    estimated_time: '1-2 weeks',
    cover_image: null,
    materials: [
      { name: 'DK weight yarn (brown)', quantity: '1 skein (100g)', estimated_cost: 4.00 },
      { name: 'DK weight yarn (cream)', quantity: '1 small ball', estimated_cost: 2.00 },
      { name: '3.5mm knitting needles', quantity: '1 pair', estimated_cost: 4.00 },
      { name: 'Toy stuffing', quantity: '1 bag', estimated_cost: 3.00 },
      { name: 'Safety eyes (12mm)', quantity: '2', estimated_cost: 1.50 },
      { name: 'Darning needle', quantity: '1', estimated_cost: 1.50 },
    ],
    steps: [
      { order: 1, title: 'Knit the Body', description: 'Cast on 10 stitches. Increase to 30 stitches over 5 rows, knit straight for 20 rows, then decrease back to 10 stitches. Leave stitches on yarn.' },
      { order: 2, title: 'Knit the Head', description: 'Cast on 8 stitches. Increase to 28 stitches, knit 16 rows, decrease to 8 stitches.' },
      { order: 3, title: 'Knit the Arms (x2)', description: 'Cast on 6 stitches, increase to 14, knit 16 rows, decrease to 6. Seam and stuff.' },
      { order: 4, title: 'Knit the Legs (x2)', description: 'Cast on 8 stitches, increase to 16, knit 18 rows, decrease to 8. Seam and stuff.' },
      { order: 5, title: 'Knit the Ears (x2)', description: 'Cast on 10 stitches, knit 6 rows, decrease to 4, cast off. Fold in half and sew.' },
      { order: 6, title: 'Assemble', description: 'Stuff and seam the body and head. Attach safety eyes before closing the head. Sew on ears, arms, and legs. Embroider a nose with cream yarn.' },
    ],
    tips: "Insert safety eyes before closing the head — they're nearly impossible to add afterwards! Stuff firmly for a toy that holds its shape.",
    cost_estimate: '£10 - £16',
    created_at: '2025-01-01T00:00:00.000Z',
  },

  // ============================================
  // CROCHET PROJECTS (10)
  // ============================================
  {
    id: 'project-021',
    title: 'Granny Square Blanket',
    description: 'The iconic granny square! Learn this classic crochet technique and join squares into a stunning blanket.',
    category: 'crochet',
    difficulty: 'intermediate',
    estimated_time: '3-4 weeks',
    cover_image: null,
    materials: [
      { name: 'DK weight yarn (assorted colours)', quantity: '6 skeins', estimated_cost: 24.00 },
      { name: '4mm crochet hook', quantity: '1', estimated_cost: 3.00 },
      { name: 'Darning needle', quantity: '1', estimated_cost: 1.50 },
    ],
    steps: [
      { order: 1, title: 'Magic Ring', description: 'Create a magic ring with your first colour. Chain 3 (counts as first treble crochet).', tip: 'If the magic ring feels tricky, chain 4 and slip stitch to form a circle instead.' },
      { order: 2, title: 'Round 1', description: 'Work 2 treble crochet into the ring, chain 2, *3 treble crochet into ring, chain 2* three more times. Slip stitch to top of ch-3 to join. You now have 4 groups of 3 trebles with ch-2 corners.' },
      { order: 3, title: 'Round 2', description: 'Change colour. Ch 3, work (3tr, ch2, 3tr) into each corner space, and 3tr into each side space. Slip stitch to join.' },
      { order: 4, title: 'Rounds 3-4', description: 'Continue adding rounds, working (3tr, ch2, 3tr) in corners and 3tr in each side space between groups. Change colours as desired.' },
      { order: 5, title: 'Make Multiple Squares', description: 'Make approximately 30-40 squares (for a throw-sized blanket) or as many as needed for your desired size.' },
      { order: 6, title: 'Join the Squares', description: 'Lay out your squares in a pleasing arrangement. Join using whip stitch or slip stitch through the back loops.' },
      { order: 7, title: 'Add a Border', description: 'Work 2 rounds of treble crochet around the entire blanket edge for a neat finish.' },
    ],
    tips: 'Keep your tension consistent across all squares so they end up the same size. Blocking individual squares before joining helps enormously.',
    cost_estimate: '£24 - £29',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-022',
    title: 'Amigurumi Cat',
    description: 'A cute little crocheted cat toy. Amigurumi uses basic stitches worked in a spiral — beginner-friendly and absolutely adorable!',
    category: 'crochet',
    difficulty: 'intermediate',
    estimated_time: '4-6 hours',
    cover_image: null,
    materials: [
      { name: 'DK cotton yarn (main colour)', quantity: '1 ball (50g)', estimated_cost: 3.00 },
      { name: 'DK cotton yarn (contrast)', quantity: 'small amount', estimated_cost: 1.50 },
      { name: '3mm crochet hook', quantity: '1', estimated_cost: 2.50 },
      { name: 'Safety eyes (8mm)', quantity: '2', estimated_cost: 1.00 },
      { name: 'Toy stuffing', quantity: 'small bag', estimated_cost: 2.50 },
      { name: 'Stitch marker', quantity: '1', estimated_cost: 1.00 },
    ],
    steps: [
      { order: 1, title: 'Head', description: 'Start with a magic ring. Work 6 dc into the ring. Increase to 36 stitches over 6 rounds (inc 6 per round). Work 6 rounds even. Decrease back to 12 stitches.', tip: 'Place a stitch marker at the start of each round — amigurumi is worked in a continuous spiral.' },
      { order: 2, title: 'Body', description: '6 dc in magic ring, increase to 30 stitches over 5 rounds. Work 10 rounds even. Decrease to 12 stitches. Stuff firmly.' },
      { order: 3, title: 'Ears (x2)', description: '6 dc in magic ring, increase to 12 over 2 rounds, work 2 rounds even. Flatten and sew to head.' },
      { order: 4, title: 'Tail', description: '6 dc in magic ring, work in spiral for 15 rounds without increasing. Stuff lightly.' },
      { order: 5, title: 'Assemble', description: 'Insert safety eyes in the head before closing. Sew head to body, attach ears and tail. Embroider a nose and mouth with contrast yarn.' },
    ],
    tips: 'Work tighter than normal to prevent stuffing showing through. Use a hook one size smaller than recommended on the yarn label.',
    cost_estimate: '£8 - £12',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-023',
    title: 'Storage Basket',
    description: 'A sturdy crocheted basket for storing craft supplies, toiletries, or small items. Uses chunky yarn for quick results.',
    category: 'crochet',
    difficulty: 'beginner',
    estimated_time: '2-3 hours',
    cover_image: null,
    materials: [
      { name: 'Chunky cotton yarn', quantity: '2 skeins (200g)', estimated_cost: 10.00 },
      { name: '6mm crochet hook', quantity: '1', estimated_cost: 3.00 },
    ],
    steps: [
      { order: 1, title: 'Base', description: 'Chain 4, slip stitch to join. Work in rounds of treble crochet, increasing evenly each round until the base measures 15cm across.' },
      { order: 2, title: 'Sides', description: 'Work one round in the back loops only to create a sharp base edge. Then continue in both loops without increasing.' },
      { order: 3, title: 'Build Up', description: 'Continue working in treble crochet rounds for approximately 12cm height (or desired height).' },
      { order: 4, title: 'Top Edge', description: 'Work a final round of double crochet for a neat, firm edge.' },
      { order: 5, title: 'Handles (Optional)', description: 'Chain 8, skip 8 stitches, rejoin. Work double crochet over the chain on the next round to create integrated handles.' },
    ],
    tips: 'Stiff cotton or jute yarn works best for baskets that hold their shape. Pull your stitches firm for structure.',
    cost_estimate: '£10 - £13',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-024',
    title: 'Crochet Coasters (Set of 4)',
    description: 'Colourful circular coasters that work up in minutes. Perfect for practising working in the round.',
    category: 'crochet',
    difficulty: 'beginner',
    estimated_time: '1-2 hours',
    cover_image: null,
    materials: [
      { name: 'DK cotton yarn (assorted colours)', quantity: '4 small balls', estimated_cost: 6.00 },
      { name: '4mm crochet hook', quantity: '1', estimated_cost: 3.00 },
    ],
    steps: [
      { order: 1, title: 'Centre', description: 'Magic ring. Work 12 treble crochet into the ring. Slip stitch to join.' },
      { order: 2, title: 'Round 2', description: 'Ch 3, 1 tr in same st, 2 tr in each st around. Slip stitch to join. (24 sts)' },
      { order: 3, title: 'Round 3', description: 'Ch 3, *2 tr in next st, 1 tr in next st* around. Slip stitch to join. (36 sts)' },
      { order: 4, title: 'Border Round', description: 'Work 1 round of double crochet in a contrasting colour for a neat edge. Fasten off.' },
      { order: 5, title: 'Make More', description: 'Repeat for the remaining coasters, mixing up your colour combinations.' },
    ],
    tips: 'Cotton yarn is best for coasters as it absorbs moisture. Mix and match colours for a cheerful set.',
    cost_estimate: '£6 - £9',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-025',
    title: 'Market Bag',
    description: 'A stretchy, reusable mesh market bag that folds up tiny but expands to hold loads of shopping.',
    category: 'crochet',
    difficulty: 'intermediate',
    estimated_time: '3-4 hours',
    cover_image: null,
    materials: [
      { name: 'DK cotton yarn', quantity: '2 skeins (200g)', estimated_cost: 8.00 },
      { name: '4mm crochet hook', quantity: '1', estimated_cost: 3.00 },
    ],
    steps: [
      { order: 1, title: 'Base', description: 'Chain 20. Work rows of treble crochet back and forth until the base measures 10cm x 20cm.' },
      { order: 2, title: 'Sides - Mesh Pattern', description: 'Join in the round. *Chain 5, skip 2 stitches, double crochet in next stitch* around. This creates the open mesh pattern.' },
      { order: 3, title: 'Continue Mesh', description: '*Chain 5, dc into centre of ch-5 loop below* around. Repeat for approximately 30cm.' },
      { order: 4, title: 'Top Edge', description: 'Work 2 rounds of treble crochet (no mesh) to create a firm top band.' },
      { order: 5, title: 'Handles', description: 'Chain 30 from each side of the bag opening. Slip stitch to attach. Work dc over each chain to strengthen the handles.' },
      { order: 6, title: 'Finish', description: "Weave in ends and give the bag a stretch — it will expand to hold much more than you'd expect!" },
    ],
    tips: 'The bag will look tiny when empty but stretches enormously! Machine wash in a pillowcase to keep it fresh.',
    cost_estimate: '£8 - £11',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-026',
    title: 'Baby Booties',
    description: 'Tiny crocheted booties that make the sweetest baby gift. Quick to make — you could finish a pair in an evening!',
    category: 'crochet',
    difficulty: 'beginner',
    estimated_time: '1-2 hours',
    cover_image: null,
    materials: [
      { name: 'Baby DK yarn', quantity: '1 ball (50g)', estimated_cost: 3.00 },
      { name: '3.5mm crochet hook', quantity: '1', estimated_cost: 2.50 },
      { name: 'Small button', quantity: '2', estimated_cost: 1.00 },
    ],
    steps: [
      { order: 1, title: 'Sole', description: 'Chain 10. Work dc around both sides of the chain, increasing at each end to form an oval sole.' },
      { order: 2, title: 'Sides', description: 'Work 3 rounds of dc in the back loop only to create the boot sides.' },
      { order: 3, title: 'Toe Shaping', description: 'Decrease across the toe area by working dc2tog 5 times across the front.' },
      { order: 4, title: 'Ankle Strap', description: 'Chain 12, attach to the other side to create a strap. Work dc over the chain.' },
      { order: 5, title: 'Finish', description: 'Sew on a small button and weave in all ends. Make the second bootie!' },
    ],
    tips: 'Use a soft baby yarn — bamboo blends are lovely and gentle on baby skin. Make a note of your stitch count for the second bootie!',
    cost_estimate: '£3 - £7',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-027',
    title: 'Flower Bouquet',
    description: 'Crochet a bouquet of flowers that will never wilt! Includes roses, daisies, and leaves.',
    category: 'crochet',
    difficulty: 'intermediate',
    estimated_time: '4-6 hours',
    cover_image: null,
    materials: [
      { name: 'DK cotton yarn (assorted colours)', quantity: '5 small balls', estimated_cost: 8.00 },
      { name: '3.5mm crochet hook', quantity: '1', estimated_cost: 2.50 },
      { name: 'Floral wire (green)', quantity: '10 stems', estimated_cost: 3.00 },
      { name: 'Green floral tape', quantity: '1 roll', estimated_cost: 2.00 },
    ],
    steps: [
      { order: 1, title: 'Rose (make 3)', description: 'Chain 40. Work 3 tr in each chain. This creates a ruffled strip that spirals into a rose when rolled. Secure with a few stitches at the base.' },
      { order: 2, title: 'Daisy (make 3)', description: 'Magic ring with yellow. 10 dc into ring. Join white. *Ch 8, sl st into next st* around for petals.' },
      { order: 3, title: 'Simple Flower (make 3)', description: 'Magic ring. *Ch 3, 2 tr in ring, ch 3, sl st in ring* 5 times for 5 petals.' },
      { order: 4, title: 'Leaves (make 6-8)', description: 'Chain 12. Work dc, htr, tr, htr, dc along the chain, creating a leaf shape. Chain 1, work the same along the other side.' },
      { order: 5, title: 'Assemble Stems', description: 'Thread floral wire through the base of each flower. Wrap the stem with green floral tape, attaching leaves as you go.' },
      { order: 6, title: 'Arrange', description: 'Group your flowers into a bouquet and tie with a ribbon. They make a gorgeous gift!' },
    ],
    tips: 'Cotton yarn holds petal shapes better than acrylic. Steam-blocking the finished flowers helps them hold their shape beautifully.',
    cost_estimate: '£8 - £16',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-028',
    title: 'Pot Holder',
    description: 'A thick, heat-resistant pot holder using double layers of cotton. A practical and satisfying make.',
    category: 'crochet',
    difficulty: 'beginner',
    estimated_time: '1-2 hours',
    cover_image: null,
    materials: [
      { name: 'Aran weight cotton yarn', quantity: '1 skein (100g)', estimated_cost: 4.50 },
      { name: '5mm crochet hook', quantity: '1', estimated_cost: 3.00 },
    ],
    steps: [
      { order: 1, title: 'Front Panel', description: 'Chain 22. Work rows of double crochet until you have a 20cm square.' },
      { order: 2, title: 'Back Panel', description: 'Make a second identical square.' },
      { order: 3, title: 'Join the Layers', description: 'Hold both panels together, wrong sides facing. Work double crochet through both layers around the edge.' },
      { order: 4, title: 'Add a Loop', description: 'At one corner, chain 12 and slip stitch to create a hanging loop.' },
      { order: 5, title: 'Finish', description: 'Fasten off and weave in ends. The double thickness provides good heat protection.' },
    ],
    tips: 'Always use 100% cotton for pot holders — synthetic yarn can melt! Making two layers ensures proper heat protection.',
    cost_estimate: '£5 - £8',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-029',
    title: 'Infinity Scarf',
    description: 'A cosy infinity scarf (also called a cowl or snood) that wraps around your neck. Warm and stylish!',
    category: 'crochet',
    difficulty: 'beginner',
    estimated_time: '2-3 hours',
    cover_image: null,
    materials: [
      { name: 'Chunky yarn', quantity: '2 skeins (200g)', estimated_cost: 10.00 },
      { name: '6mm crochet hook', quantity: '1', estimated_cost: 3.00 },
    ],
    steps: [
      { order: 1, title: 'Foundation Chain', description: 'Chain 120 loosely. Join with a slip stitch to form a ring, being careful not to twist the chain.' },
      { order: 2, title: 'Round 1', description: 'Chain 3 (counts as treble crochet), treble crochet in each chain around. Slip stitch to join.' },
      { order: 3, title: 'Continue', description: 'Repeat for 12-15 rounds, or until the scarf is your desired width (15-20cm is ideal).' },
      { order: 4, title: 'Final Round', description: 'Work one round of double crochet for a neat edge.' },
      { order: 5, title: 'Finish', description: 'Fasten off and weave in all ends. Block lightly if needed.' },
    ],
    tips: 'Choose a soft yarn that feels nice against your skin — merino wool or a soft acrylic are perfect. This scarf also looks great in two alternating colours.',
    cost_estimate: '£10 - £13',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-030',
    title: 'Phone Case',
    description: 'A snug crocheted phone case to protect your device in style. A quick project you can finish in one sitting!',
    category: 'crochet',
    difficulty: 'beginner',
    estimated_time: '1-2 hours',
    cover_image: null,
    materials: [
      { name: 'DK cotton yarn', quantity: '1 ball (50g)', estimated_cost: 3.00 },
      { name: '3.5mm crochet hook', quantity: '1', estimated_cost: 2.50 },
      { name: 'Button', quantity: '1', estimated_cost: 0.50 },
    ],
    steps: [
      { order: 1, title: 'Measure Your Phone', description: 'Place your phone on the yarn and crochet a test swatch to calculate how many stitches you need for the width.' },
      { order: 2, title: 'Base Chain', description: 'Chain enough stitches to go around your phone plus 2cm ease. Join to work in the round.' },
      { order: 3, title: 'Body', description: 'Work in double crochet rounds until the case reaches the top of your phone.' },
      { order: 4, title: 'Flap', description: 'Work back and forth in rows for the flap. Work 6-8 rows, decreasing on each side to create a pointed flap.' },
      { order: 5, title: 'Button Loop', description: 'At the point of the flap, chain 8 and slip stitch back to create a button loop.' },
      { order: 6, title: 'Finish', description: 'Sew on the button and weave in all ends.' },
    ],
    tips: 'Work slightly tighter than normal for a snug fit. Test the fit frequently as you go!',
    cost_estimate: '£3 - £6',
    created_at: '2025-01-01T00:00:00.000Z',
  },

  // ============================================
  // EMBROIDERY PROJECTS (5)
  // ============================================
  {
    id: 'project-031',
    title: 'Floral Hoop Art',
    description: 'A beautiful floral wreath embroidered in a hoop — perfect wall décor and a wonderful introduction to hand embroidery.',
    category: 'embroidery',
    difficulty: 'beginner',
    estimated_time: '4-6 hours',
    cover_image: null,
    materials: [
      { name: 'Embroidery hoop (15cm)', quantity: '1', estimated_cost: 3.00 },
      { name: 'Cotton fabric (plain)', quantity: '25cm x 25cm', estimated_cost: 2.00 },
      { name: 'Embroidery thread (DMC assorted)', quantity: '6 colours', estimated_cost: 6.00 },
      { name: 'Embroidery needle', quantity: '1', estimated_cost: 1.00 },
      { name: 'Water-soluble pen', quantity: '1', estimated_cost: 2.50 },
    ],
    steps: [
      { order: 1, title: 'Prepare Your Hoop', description: 'Place the fabric in the hoop, pulling it taut like a drum. Tighten the screw at the top.' },
      { order: 2, title: 'Transfer the Design', description: 'Use the water-soluble pen to draw a simple circle of flowers: 5 main flowers, connected by stems and leaves.', tip: "Start with simple shapes — you don't need to be an artist! Even basic circles and ovals make lovely flowers." },
      { order: 3, title: 'Stitch the Stems', description: 'Using 2 strands of green thread, work stem stitch or back stitch along each stem line.' },
      { order: 4, title: 'Embroider the Leaves', description: 'Use lazy daisy stitch (detached chain) for small leaves along the stems.' },
      { order: 5, title: 'Stitch the Flowers', description: 'Mix techniques: satin stitch for filled petals, French knots for flower centres, lazy daisy for small flowers.' },
      { order: 6, title: 'Add Details', description: 'Add tiny French knots between the flowers as filler. Use contrasting colours for visual interest.' },
      { order: 7, title: 'Finish the Back', description: 'Trim the excess fabric to 3cm around the hoop. Fold it to the back and glue with fabric glue, or sew a running stitch to gather it in.' },
    ],
    tips: 'Use 2 strands of thread for most stitches (the full 6-strand floss is too thick). Iron the fabric before hooping for the smoothest surface.',
    cost_estimate: '£10 - £15',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-032',
    title: 'Hand-Embroidered Monogram',
    description: 'Personalise a handkerchief, tote, or clothing with a beautifully embroidered letter initial.',
    category: 'embroidery',
    difficulty: 'intermediate',
    estimated_time: '3-4 hours',
    cover_image: null,
    materials: [
      { name: 'Plain cotton item (hanky, napkin, or fabric)', quantity: '1', estimated_cost: 3.00 },
      { name: 'Embroidery hoop (10cm)', quantity: '1', estimated_cost: 2.50 },
      { name: 'Embroidery thread (DMC)', quantity: '2-3 colours', estimated_cost: 3.00 },
      { name: 'Embroidery needle', quantity: '1', estimated_cost: 1.00 },
      { name: 'Transfer pen or pencil', quantity: '1', estimated_cost: 2.00 },
    ],
    steps: [
      { order: 1, title: 'Choose Your Letter', description: 'Select a serif font letter and print or trace it at your desired size (4-6cm tall works well).' },
      { order: 2, title: 'Transfer the Design', description: 'Place the fabric in the hoop. Transfer the letter using a light box or carbon paper.' },
      { order: 3, title: 'Outline with Split Stitch', description: 'Using 2 strands, work split stitch along the outline of the letter for a clean edge.' },
      { order: 4, title: 'Fill with Satin Stitch', description: 'Fill the letter with satin stitch, keeping your stitches parallel and close together.', tip: 'For wide sections, split the satin stitch into smaller sections to prevent loose, saggy stitches.' },
      { order: 5, title: 'Add Flourishes', description: 'Add small decorative elements: a floral sprig, dots, or a simple border around the letter.' },
      { order: 6, title: 'Finish', description: 'Remove from the hoop, press from the back with a warm iron, and display or gift your work.' },
    ],
    tips: 'Satin stitch looks best when every stitch is parallel. Work slowly and adjust as you go. A hoop keeps the fabric taut for even stitches.',
    cost_estimate: '£6 - £12',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-033',
    title: 'Cross-Stitch Bookmark',
    description: 'A sweet cross-stitch bookmark with a simple geometric or floral pattern. A wonderful portable project!',
    category: 'embroidery',
    difficulty: 'beginner',
    estimated_time: '2-3 hours',
    cover_image: null,
    materials: [
      { name: 'Aida cloth (14-count)', quantity: '1 strip 5cm x 18cm', estimated_cost: 2.00 },
      { name: 'Embroidery thread (DMC)', quantity: '3-4 colours', estimated_cost: 4.00 },
      { name: 'Cross-stitch needle (tapestry)', quantity: '1', estimated_cost: 1.00 },
      { name: 'Small scissors', quantity: '1', estimated_cost: 3.00 },
    ],
    steps: [
      { order: 1, title: 'Prepare the Fabric', description: 'Cut your Aida cloth to approximately 5cm x 18cm. Fold masking tape over the edges to prevent fraying.' },
      { order: 2, title: 'Find the Centre', description: 'Fold the fabric in half both ways and mark the centre point with a pin. Start stitching from the centre of your design.' },
      { order: 3, title: 'Follow the Pattern', description: 'Using 2 strands of thread, work cross stitches following a simple pattern: hearts, stars, or a geometric border.', tip: 'Each X should cross in the same direction for a neat finish — bottom-left to top-right first, then bottom-right to top-left.' },
      { order: 4, title: 'Complete the Design', description: 'Work outwards from the centre, completing one colour at a time to avoid constantly rethreading.' },
      { order: 5, title: 'Backstitch Outlines', description: 'Add backstitch outlines using 1 strand of a dark colour for definition.' },
      { order: 6, title: 'Finish', description: 'Trim the Aida to 1cm around the design. Fold the edges under and press, or add a felt backing.' },
    ],
    tips: 'Cross stitch on Aida cloth is wonderfully straightforward — the holes guide your needle perfectly. Great for watching telly!',
    cost_estimate: '£5 - £10',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-034',
    title: 'Embroidered Patch',
    description: 'Design and stitch your own wearable patch. Iron it onto a jacket, bag, or hat for instant personalisation!',
    category: 'embroidery',
    difficulty: 'intermediate',
    estimated_time: '3-4 hours',
    cover_image: null,
    materials: [
      { name: 'Cotton twill or canvas', quantity: 'small piece', estimated_cost: 2.00 },
      { name: 'Embroidery hoop (8cm)', quantity: '1', estimated_cost: 2.50 },
      { name: 'Embroidery thread (DMC)', quantity: '4-5 colours', estimated_cost: 5.00 },
      { name: 'Iron-on adhesive (HeatnBond)', quantity: 'small piece', estimated_cost: 2.00 },
      { name: 'Embroidery needle', quantity: '1', estimated_cost: 1.00 },
    ],
    steps: [
      { order: 1, title: 'Design Your Patch', description: 'Sketch a simple design — a small motif like a flower, mushroom, lightning bolt, or your initials. Keep it under 6cm.' },
      { order: 2, title: 'Transfer and Hoop', description: 'Transfer the design onto the fabric and secure in a small hoop.' },
      { order: 3, title: 'Fill with Satin Stitch', description: 'Work satin stitch to fill large areas of colour. Use 3 strands for good coverage.' },
      { order: 4, title: 'Add Details', description: 'Use backstitch for outlines and French knots for texture.' },
      { order: 5, title: 'Cut Out the Patch', description: 'Remove from hoop. Apply iron-on adhesive to the back following package instructions. Cut around the design, leaving a 3mm border.' },
      { order: 6, title: 'Finish the Edge', description: 'Work blanket stitch around the raw edge to seal it and add a professional finish.' },
      { order: 7, title: 'Apply', description: 'Iron the patch onto your chosen garment or accessory. Hand-stitch the edges for extra durability.' },
    ],
    tips: 'Bold, simple designs work best for patches. Outline everything in backstitch for a clean, graphic look.',
    cost_estimate: '£6 - £13',
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'project-035',
    title: 'Stitch Sampler',
    description: "Learn 10+ embroidery stitches by creating a beautiful sampler. A reference piece you'll treasure as you develop your skills.",
    category: 'embroidery',
    difficulty: 'beginner',
    estimated_time: '1-2 weeks',
    cover_image: null,
    materials: [
      { name: 'Cotton fabric (natural)', quantity: '30cm x 30cm', estimated_cost: 3.00 },
      { name: 'Embroidery hoop (20cm)', quantity: '1', estimated_cost: 4.00 },
      { name: 'Embroidery thread (DMC assorted)', quantity: '8-10 colours', estimated_cost: 10.00 },
      { name: 'Embroidery needle', quantity: '1', estimated_cost: 1.00 },
      { name: 'Water-soluble pen', quantity: '1', estimated_cost: 2.50 },
    ],
    steps: [
      { order: 1, title: 'Plan Your Layout', description: 'Divide your fabric into 10 sections with the water-soluble pen. Each section will showcase a different stitch.' },
      { order: 2, title: 'Running Stitch', description: 'The most basic stitch — in and out at even intervals. Try straight lines and curves.' },
      { order: 3, title: 'Back Stitch', description: 'Creates a solid line. Work backwards to fill gaps between running stitches.' },
      { order: 4, title: 'Stem Stitch', description: 'Perfect for curves and plant stems. Keep the thread always on the same side of the needle.' },
      { order: 5, title: 'Satin Stitch', description: 'Fill shapes with parallel stitches laid closely together. Practice on a circle and a leaf shape.' },
      { order: 6, title: 'French Knots', description: 'Wrap the thread around the needle twice, then push through close to where you came up. Takes practice!', tip: 'Hold the working thread taut with your non-needle hand as you push the needle through — this prevents messy knots.' },
      { order: 7, title: 'Lazy Daisy', description: 'Create petal shapes with detached chain stitches arranged in a circle.' },
      { order: 8, title: 'Chain Stitch', description: 'A versatile stitch for lines and borders. Each loop catches the next.' },
      { order: 9, title: 'Blanket Stitch', description: 'A decorative edge stitch. Practice along a straight line, then try around a shape.' },
      { order: 10, title: 'Label Your Sampler', description: 'Use back stitch to write the name of each stitch next to its section. Frame in the hoop and hang on your wall!' },
    ],
    tips: 'This sampler becomes your personal reference guide. Take your time with each stitch — quality over speed. Use 2 strands throughout unless otherwise noted.',
    cost_estimate: '£10 - £21',
    created_at: '2025-01-01T00:00:00.000Z',
  },
];

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_stitch',
    key: 'first_stitch',
    name: 'First Stitch',
    description: 'Start your first project',
    icon: 'scissors',
    xp_reward: 25,
    criteria: { type: 'projects_started', count: 1 },
  },
  {
    id: 'thread_collector',
    key: 'thread_collector',
    name: 'Thread Collector',
    description: 'Start 5 projects',
    icon: 'layers',
    xp_reward: 50,
    criteria: { type: 'projects_started', count: 5 },
  },
  {
    id: 'finished_article',
    key: 'finished_article',
    name: 'Finished Article',
    description: 'Complete your first project',
    icon: 'check-circle',
    xp_reward: 50,
    criteria: { type: 'projects_completed', count: 1 },
  },
  {
    id: 'yarn_whisperer',
    key: 'yarn_whisperer',
    name: 'Yarn Whisperer',
    description: 'Complete your first knitting project',
    icon: 'heart',
    xp_reward: 50,
    criteria: { type: 'category_completed', category: 'knitting', count: 1 },
  },
  {
    id: 'needle_ninja',
    key: 'needle_ninja',
    name: 'Needle Ninja',
    description: 'Complete 3 sewing projects',
    icon: 'zap',
    xp_reward: 75,
    criteria: { type: 'category_completed', category: 'sewing', count: 3 },
  },
  {
    id: 'hook_line_sinker',
    key: 'hook_line_sinker',
    name: 'Hook, Line & Sinker',
    description: 'Complete your first crochet project',
    icon: 'anchor',
    xp_reward: 50,
    criteria: { type: 'category_completed', category: 'crochet', count: 1 },
  },
  {
    id: 'snap_happy',
    key: 'snap_happy',
    name: 'Snap Happy',
    description: 'Upload 10 photos',
    icon: 'camera',
    xp_reward: 50,
    criteria: { type: 'photos_uploaded', count: 10 },
  },
  {
    id: 'perfectionist',
    key: 'perfectionist',
    name: 'Perfectionist',
    description: 'Give a project 5 stars',
    icon: 'star',
    xp_reward: 25,
    criteria: { type: 'five_star_rating', count: 1 },
  },
  {
    id: 'night_owl',
    key: 'night_owl',
    name: 'Night Owl',
    description: 'Log crafting time after 10pm',
    icon: 'moon',
    xp_reward: 25,
    criteria: { type: 'night_crafting', count: 1 },
  },
  {
    id: 'marathon_maker',
    key: 'marathon_maker',
    name: 'Marathon Maker',
    description: 'Log 50+ hours total crafting',
    icon: 'clock',
    xp_reward: 100,
    criteria: { type: 'hours_logged', count: 50 },
  },
  {
    id: 'material_girl',
    key: 'material_girl',
    name: 'Material Girl',
    description: 'Check off all materials for 3 projects',
    icon: 'shopping-bag',
    xp_reward: 50,
    criteria: { type: 'materials_complete', count: 3 },
  },
  {
    id: 'speed_demon',
    key: 'speed_demon',
    name: 'Speed Demon',
    description: 'Complete a project in under a week',
    icon: 'timer',
    xp_reward: 75,
    criteria: { type: 'fast_completion', days: 7 },
  },
  {
    id: 'completionist',
    key: 'completionist',
    name: 'Completionist',
    description: 'Complete all projects in one category',
    icon: 'trophy',
    xp_reward: 200,
    criteria: { type: 'category_all_complete', count: 1 },
  },
  {
    id: 'renaissance_crafter',
    key: 'renaissance_crafter',
    name: 'Renaissance Crafter',
    description: 'Complete a project in each category',
    icon: 'palette',
    xp_reward: 150,
    criteria: { type: 'all_categories', count: 4 },
  },
  {
    id: 'streak_master',
    key: 'streak_master',
    name: 'Streak Master',
    description: 'Maintain a 30-day crafting streak',
    icon: 'flame',
    xp_reward: 200,
    criteria: { type: 'streak', count: 30 },
  },
];
