/**
 * Curated craft tutorials from DROPS Design (garnstudio.com).
 * All patterns are free and include real product photos.
 * Each tutorial links to the full pattern on the original site.
 */

export interface CraftTutorial {
  id: string;
  title: string;
  description: string;
  imageUrl: string;
  sourceUrl: string;
  sourceName: string;
  category: 'knitting' | 'crochet';
  subcategory: string;
  tags: string[];
}

export const TUTORIALS: CraftTutorial[] = [
  // ===== WOMEN'S SWEATERS =====
  {
    id: 'drops-267-27',
    title: 'Sand Walk Sweater',
    description: 'Knitted jumper in stocking stitch with boat neck and diagonal shoulder. Knitted top down.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/267/27/27-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=12650&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Sweaters',
    tags: ['women', 'sweater', 'top-down', 'summer'],
  },
  {
    id: 'drops-231-53',
    title: 'Daisy Lane',
    description: 'Knitted sweater with round yoke and multi-coloured pattern. Worked top down in stockinette stitch.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/231/53/53d-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=10726&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Sweaters',
    tags: ['women', 'sweater', 'colourwork', 'yoke'],
  },
  {
    id: 'drops-259-1',
    title: 'April Snow',
    description: 'Knitted sweater with round yoke and Nordic pattern. Worked top down in stockinette stitch.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/259/1/1-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=12116&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Sweaters',
    tags: ['women', 'sweater', 'nordic', 'winter'],
  },
  {
    id: 'drops-267-15',
    title: 'Elodie Lace Sweater',
    description: 'Knitted sweater with lace pattern and round yoke. Elegant design for spring and summer.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/267/15/15-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=12644&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Sweaters',
    tags: ['women', 'sweater', 'lace', 'spring'],
  },
  {
    id: 'drops-268-24',
    title: 'Sunlit Grid Top',
    description: 'Knitted top with grid pattern. Perfect lightweight summer garment with short sleeves.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/268/24/24-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=12648&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Sweaters',
    tags: ['women', 'top', 'summer', 'lightweight'],
  },
  {
    id: 'drops-268-3',
    title: 'Perfectly Bee Sweater',
    description: 'Knitted sweater with honeycomb textured pattern. Cosy and warm with a modern twist.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/268/3/3-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=12663&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Sweaters',
    tags: ['women', 'sweater', 'textured', 'cosy'],
  },
  {
    id: 'drops-266-11',
    title: 'White Dreams Sweater',
    description: 'Elegant knitted sweater in white with lace details. Light and airy for warmer months.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/266/11/11-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=12646&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Sweaters',
    tags: ['women', 'sweater', 'lace', 'elegant'],
  },
  {
    id: 'drops-267-36',
    title: 'Strawberry Pie Tee',
    description: 'Crocheted top with colourful strawberry motif. Fun summer project with fruity design.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/267/36/36-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=12661&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'crochet',
    subcategory: 'Sweaters',
    tags: ['women', 'top', 'crochet', 'summer', 'colourful'],
  },

  // ===== HATS & ACCESSORIES =====
  {
    id: 'drops-261-37',
    title: 'Sunny Bloom Hat',
    description: 'Knitted hat with floral colourwork pattern. Bright and cheerful for spring walks.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/261/37/37-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=12665&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Accessories',
    tags: ['women', 'hat', 'colourwork', 'spring'],
  },
  {
    id: 'drops-214-67',
    title: 'Winter Smiles Hat',
    description: 'Knitted hat with pompom and smiling face pattern. Warm and fun for cold days.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/214/67/67-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=10010&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Accessories',
    tags: ['women', 'hat', 'winter', 'pompom'],
  },
  {
    id: 'drops-196-23',
    title: 'Inner Circle',
    description: 'Knitted hat with beautiful circular colourwork pattern. A classic Nordic design.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/196/23/23-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=8779&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Accessories',
    tags: ['women', 'hat', 'nordic', 'colourwork'],
  },
  {
    id: 'drops-180-2',
    title: 'Perles du Nord',
    description: 'Knitted hat and neck warmer set with intricate Nordic pattern in multiple colours.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/180/2/2-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=8046&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Accessories',
    tags: ['women', 'hat', 'scarf', 'set', 'nordic'],
  },
  {
    id: 'drops-242-22',
    title: 'Cardinal Song',
    description: 'Knitted headband with textured pattern. Quick project, perfect for beginners.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/242/22/22-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=11639&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Accessories',
    tags: ['women', 'headband', 'quick', 'beginner'],
  },

  // ===== SCARVES & WRAPS =====
  {
    id: 'drops-261-4',
    title: 'Misty Fjord Hood',
    description: 'Knitted hood with beautiful cable pattern. Cosy alternative to a hat for winter.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/261/4/4b-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=12334&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Scarves',
    tags: ['women', 'hood', 'cable', 'winter'],
  },
  {
    id: 'drops-253-61',
    title: 'Winter Hug Hood',
    description: 'Warm knitted hood with ribbed texture. Wraps around for extra warmth on cold days.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/253/61/61-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=12086&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Scarves',
    tags: ['women', 'hood', 'winter', 'warm'],
  },
  {
    id: 'drops-229-12',
    title: 'Spring Catch',
    description: 'Light knitted shawl with lace border. Delicate wrap for spring evenings.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/229/12/12-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=10740&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Scarves',
    tags: ['women', 'shawl', 'lace', 'spring'],
  },
  {
    id: 'drops-151-8',
    title: 'Ladylike',
    description: 'Elegant knitted shawl with intricate lace pattern. A timeless accessory.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/151/8/8-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=6326&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Scarves',
    tags: ['women', 'shawl', 'lace', 'elegant'],
  },

  // ===== BABY =====
  {
    id: 'drops-b20-9',
    title: 'Sky High',
    description: 'Knitted baby set with hat, jumpsuit, and socks in soft colours. Adorable for newborns.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/b20/9/9-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=4905&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Baby',
    tags: ['baby', 'set', 'jumpsuit', 'hat', 'socks'],
  },
  {
    id: 'drops-b42-4',
    title: 'Little Bee Cardigan',
    description: 'Knitted baby cardigan with bee-inspired pattern. Sweet and cosy for little ones.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/b42/4/4-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=10675&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Baby',
    tags: ['baby', 'cardigan', 'cute'],
  },
  {
    id: 'drops-b42-5',
    title: 'Dream in Blue',
    description: 'Knitted baby blanket in soft blue. A beautiful gift for a baby shower.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/b42/5/5-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=10680&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Baby',
    tags: ['baby', 'blanket', 'gift'],
  },
  {
    id: 'drops-b25-11',
    title: 'Bedtime Stories',
    description: 'Knitted baby blanket with textured pattern. Soft and cuddly for bedtime.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/b25/11/11-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=6593&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Baby',
    tags: ['baby', 'blanket', 'textured'],
  },
  {
    id: 'drops-b21-21',
    title: 'Sweet Strawberry',
    description: 'Adorable knitted baby hat with strawberry design. Fun and colourful for little ones.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/b21/21/21-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=5447&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Baby',
    tags: ['baby', 'hat', 'cute', 'fruit'],
  },
  {
    id: 'drops-b42-10',
    title: 'Little Pearl Socks',
    description: 'Tiny knitted socks for babies. Quick project with a sweet pearl pattern.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/b42/10/10-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=10691&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Baby',
    tags: ['baby', 'socks', 'quick'],
  },

  // ===== CHILDREN =====
  {
    id: 'drops-s49-7',
    title: 'Gentle Day Sweater',
    description: 'Knitted children\'s sweater with round yoke. Comfortable and stylish for everyday wear.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/s49/7/7-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=12265&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Children',
    tags: ['children', 'sweater', 'everyday'],
  },
  {
    id: 'drops-s41-34',
    title: 'Dancing Bunny Socks',
    description: 'Knitted children\'s socks with bunny pattern. Adorable and fun to wear.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/s41/34/34-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=10795&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Children',
    tags: ['children', 'socks', 'bunny', 'cute'],
  },
  {
    id: 'drops-s50-10',
    title: 'Magic Mist Sweater',
    description: 'Children\'s sweater with gradient colour effect. Magical look for little ones.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/s50/10/10-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=12547&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Children',
    tags: ['children', 'sweater', 'gradient', 'colourful'],
  },
  {
    id: 'drops-s50-13',
    title: 'Sunset Sprinkles Sweater',
    description: 'Knitted children\'s sweater with playful colourwork pattern inspired by sunset colours.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/s50/13/13-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=12544&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Children',
    tags: ['children', 'sweater', 'colourwork'],
  },
  {
    id: 'drops-s34-30',
    title: 'Reykjavik Kids',
    description: 'Knitted children\'s sweater with classic Icelandic pattern. Traditional Nordic charm.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/s34/30/30-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=9450&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Children',
    tags: ['children', 'sweater', 'nordic', 'icelandic'],
  },

  // ===== HOME & INTERIOR =====
  {
    id: 'drops-265-34',
    title: 'Gentle Spring Seating Pad',
    description: 'Knitted round seating pad with spring-inspired pattern. Cosy addition to any chair.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/265/34/34-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=12681&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Home',
    tags: ['home', 'cushion', 'spring', 'decor'],
  },
  {
    id: 'drops-215-46',
    title: 'Poetry Reading Pillow',
    description: 'Knitted cushion cover with cable pattern. Perfect for a cosy reading nook.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/215/46/46-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=10051&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Home',
    tags: ['home', 'pillow', 'cable', 'decor'],
  },
  {
    id: 'drops-0-1688',
    title: 'Pastel Treasure',
    description: 'Knitted storage basket in pastel colours. Practical and pretty for any room.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/0/1688/1688d-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=12679&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Home',
    tags: ['home', 'basket', 'storage', 'pastel'],
  },
  {
    id: 'drops-265-1',
    title: 'Country Cottage Blanket',
    description: 'Crocheted blanket with granny squares in country colours. Warm and charming.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/265/1/1-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=12562&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'crochet',
    subcategory: 'Home',
    tags: ['home', 'blanket', 'granny-square', 'crochet'],
  },
  {
    id: 'drops-159-26',
    title: 'Waffle Love',
    description: 'Knitted dishcloth with waffle texture. Quick and useful kitchen project.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/159/26/26-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=6870&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Home',
    tags: ['home', 'dishcloth', 'kitchen', 'quick'],
  },
  {
    id: 'drops-0-545',
    title: 'Cosy Bunnies',
    description: 'Knitted egg warmers shaped like bunnies. Adorable Easter table decoration.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/0/545/545-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=4127&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Home',
    tags: ['home', 'easter', 'bunny', 'decoration'],
  },

  // ===== TOYS & AMIGURUMI =====
  {
    id: 'drops-0-769',
    title: 'Chicken Little',
    description: 'Crocheted chicken toy. Fun and colourful amigurumi project for all skill levels.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/0/769/769-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=5116&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'crochet',
    subcategory: 'Toys',
    tags: ['toy', 'amigurumi', 'chicken', 'animal'],
  },
  {
    id: 'drops-b25-8',
    title: 'Mr. Bunny',
    description: 'Knitted bunny toy with scarf. A cuddly companion for little ones.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/b25/8/8b-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=6590&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Toys',
    tags: ['toy', 'bunny', 'stuffed-animal', 'gift'],
  },
  {
    id: 'drops-b46-18',
    title: 'The Bunny Bunch',
    description: 'Set of knitted bunny toys in different colours. Perfect for a collection or gift set.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/b46/18/18e-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=11293&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Toys',
    tags: ['toy', 'bunny', 'set', 'colourful'],
  },
  {
    id: 'drops-s37-21',
    title: 'Bob the Dinosaur',
    description: 'Crocheted dinosaur toy. A friendly dino companion for kids who love prehistoric creatures.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/s37/21/21-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=9909&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'crochet',
    subcategory: 'Toys',
    tags: ['toy', 'dinosaur', 'amigurumi', 'children'],
  },
  {
    id: 'drops-b29-10',
    title: 'Sweet Betty',
    description: 'Knitted doll with removable clothes. Hours of imaginative play for children.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/b29/10/10-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=8032&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Toys',
    tags: ['toy', 'doll', 'clothes', 'children'],
  },
  {
    id: 'drops-0-844',
    title: 'Bill & Ted',
    description: 'Crocheted bear and bunny duo. Two adorable friends in one pattern.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/0/844/844-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=5628&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'crochet',
    subcategory: 'Toys',
    tags: ['toy', 'bear', 'bunny', 'amigurumi'],
  },
  {
    id: 'drops-s23-56',
    title: 'Tutti Frutti',
    description: 'Crocheted fruit toys — apple, pear, and orange. Colourful play food for kids.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/s23/56/56-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=5835&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'crochet',
    subcategory: 'Toys',
    tags: ['toy', 'fruit', 'play-food', 'colourful'],
  },

  // ===== CHRISTMAS & HOLIDAY =====
  {
    id: 'drops-s50-4',
    title: 'Blue Holly Sweater',
    description: 'Knitted children\'s Christmas sweater with holly pattern. Festive and fun.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/s50/4/4-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=12487&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Christmas',
    tags: ['christmas', 'children', 'sweater', 'festive'],
  },
  {
    id: 'drops-228-49',
    title: 'Merry Stars',
    description: 'Knitted Christmas stockings with star pattern. Hang them by the fireplace.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/228/49/49-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=10561&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Christmas',
    tags: ['christmas', 'stocking', 'star', 'decoration'],
  },
  {
    id: 'drops-s26-14',
    title: 'Little Hedda',
    description: 'Knitted angel Christmas ornament. Delicate and beautiful tree decoration.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/s26/14/14e-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=7022&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Christmas',
    tags: ['christmas', 'angel', 'ornament', 'decoration'],
  },
  {
    id: 'drops-261-72',
    title: 'Frosty Town Socks',
    description: 'Knitted Christmas socks with town and snow scene. Cosy festive footwear.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/261/72/72-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=12530&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Christmas',
    tags: ['christmas', 'socks', 'winter', 'colourwork'],
  },
  {
    id: 'drops-0-1396',
    title: 'Christmas Shine',
    description: 'Crocheted star Christmas decorations. Quick to make and perfect for gift-giving.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/0/1396/1396-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=8324&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'crochet',
    subcategory: 'Christmas',
    tags: ['christmas', 'star', 'decoration', 'quick'],
  },
  {
    id: 'drops-0-1460',
    title: 'Christmas Claps',
    description: 'Knitted mittens with Christmas pattern. Warm hands with festive spirit.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/0/1460/1460e-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=9443&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: 'Christmas',
    tags: ['christmas', 'mittens', 'colourwork', 'warm'],
  },

  // ===== MEN'S =====
  {
    id: 'drops-233-24',
    title: 'Variety',
    description: 'Knitted men\'s sweater with textured pattern. Modern and comfortable everyday wear.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/233/24/24d-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=11385&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: "Men's",
    tags: ['men', 'sweater', 'textured', 'everyday'],
  },
  {
    id: 'drops-260-18',
    title: 'Midnight Tide Sweater',
    description: 'Men\'s sweater with wave-inspired colourwork. Striking design in dark tones.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/260/18/18c-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=12549&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: "Men's",
    tags: ['men', 'sweater', 'colourwork', 'dark'],
  },
  {
    id: 'drops-260-22',
    title: 'Slate Coast Sweater',
    description: 'Men\'s sweater in slate grey with subtle texture. Classic and versatile.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/260/22/22-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=12550&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: "Men's",
    tags: ['men', 'sweater', 'classic', 'grey'],
  },
  {
    id: 'drops-135-3',
    title: 'Dreams of Aran',
    description: 'Classic men\'s Aran sweater with cable pattern. Timeless Irish-inspired design.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/135/3/3-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=4535&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: "Men's",
    tags: ['men', 'sweater', 'cable', 'aran', 'irish'],
  },
  {
    id: 'drops-208-3',
    title: 'Reykjavik',
    description: 'Men\'s sweater with Icelandic yoke pattern. Bold Nordic design in natural colours.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/208/3/3c-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=9434&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: "Men's",
    tags: ['men', 'sweater', 'icelandic', 'nordic', 'yoke'],
  },
  {
    id: 'drops-224-21',
    title: 'Lucky Wish',
    description: 'Men\'s sweater with textured knit pattern. Comfortable fit for casual wear.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/224/21/21b-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=10419&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'knitting',
    subcategory: "Men's",
    tags: ['men', 'sweater', 'textured', 'casual'],
  },

  // ===== CROCHET HIGHLIGHTS =====
  {
    id: 'drops-268-2',
    title: 'Harvest Dress',
    description: 'Crocheted dress with beautiful stitch pattern. Flowy and feminine for summer.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/268/2/2-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=12643&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'crochet',
    subcategory: 'Sweaters',
    tags: ['women', 'dress', 'summer', 'elegant'],
  },
  {
    id: 'drops-266-4',
    title: 'Blue Country Wrap',
    description: 'Crocheted wrap in beautiful blue tones. Versatile accessory for any season.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/266/4/4-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=12653&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'crochet',
    subcategory: 'Scarves',
    tags: ['women', 'wrap', 'blue', 'versatile'],
  },
  {
    id: 'drops-177-24',
    title: 'Aegean',
    description: 'Crocheted poncho with lace pattern. Light and breezy Mediterranean-inspired design.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/177/24/24-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=7924&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'crochet',
    subcategory: 'Scarves',
    tags: ['women', 'poncho', 'lace', 'summer'],
  },
  {
    id: 'drops-223-28',
    title: 'Red River Cave',
    description: 'Crocheted shawl with striking geometric pattern. Bold statement piece in warm colours.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/223/28/28-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=10254&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'crochet',
    subcategory: 'Scarves',
    tags: ['women', 'shawl', 'geometric', 'bold'],
  },
  {
    id: 'drops-266-37',
    title: 'Coconut Cream Skirt',
    description: 'Crocheted skirt in cream with textured pattern. Unique handmade fashion piece.',
    imageUrl: 'https://images.garnstudio.com/drops/mag/266/37/37-2.jpg',
    sourceUrl: 'https://www.garnstudio.com/pattern.php?id=12640&cid=19&lang=en',
    sourceName: 'DROPS Design',
    category: 'crochet',
    subcategory: 'Sweaters',
    tags: ['women', 'skirt', 'summer', 'fashion'],
  },
];

// ---- Helpers ----

export function getTutorialsBySubcategory(subcategory: string): CraftTutorial[] {
  return TUTORIALS.filter((t) => t.subcategory === subcategory);
}

export function getTutorialsByCategory(category: 'knitting' | 'crochet'): CraftTutorial[] {
  return TUTORIALS.filter((t) => t.category === category);
}

export function searchTutorials(query: string): CraftTutorial[] {
  const q = query.toLowerCase().trim();
  if (!q) return TUTORIALS;
  return TUTORIALS.filter(
    (t) =>
      t.title.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.tags.some((tag) => tag.includes(q)) ||
      t.subcategory.toLowerCase().includes(q),
  );
}

export function getTutorialById(id: string): CraftTutorial | undefined {
  return TUTORIALS.find((t) => t.id === id);
}

export const SUBCATEGORIES = [
  { key: 'Sweaters', label: 'Sweaters & Tops', emoji: '👕' },
  { key: 'Accessories', label: 'Hats & Accessories', emoji: '🧢' },
  { key: 'Scarves', label: 'Scarves & Wraps', emoji: '🧣' },
  { key: 'Baby', label: 'Baby', emoji: '👶' },
  { key: 'Children', label: 'Children', emoji: '🧒' },
  { key: 'Home', label: 'Home & Decor', emoji: '🏠' },
  { key: 'Toys', label: 'Toys & Amigurumi', emoji: '🧸' },
  { key: 'Christmas', label: 'Christmas & Holiday', emoji: '🎄' },
  { key: "Men's", label: "Men's", emoji: '👔' },
] as const;
